name: Simple Terraform Workflow

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Choose: plan, apply or destroy"
        required: true
        default: plan
        type: choice
        options:
          - plan
          - apply
          - destroy

permissions:
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      TF_DIR: infra
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      AWS_DEFAULT_REGION: "ap-south-1"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
 
      - name: Terraform Init
        working-directory: ${{ env.TF_DIR }}
        run: terraform init -input=false

      - name: Run Terraform Plan
        working-directory: ${{ env.TF_DIR }}
        run: terraform plan

      - name: Run Terraform Apply
        if: ${{ github.event.inputs.action == apply' }}
        working-directory: ${{ env.TF_DIR }}
        run: terraform apply --auto-approve

      - name: Run Terraform Destroy
        if: ${{ github.event.inputs.action == destroy' }}
        working-directory: ${{ env.TF_DIR }}
        run: terraform destroy --auto-approve