name: Greeting

on:
  push:
    branches:
      - master

env:
  DAY_OF_THE_WEEK: Monday

jobs:
  greeting-job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Mona its Monday"
        run: "$Greeting My name is $Name and today is $DAY_OF_THE_WEEK !"
        env:
         Name: Mona