name: Greeting

on:
  push:
    branches:
      - master

env:
  DAY_OF_THE_WEEK: Monday
  Greeting: Hello
  Name: Mona

jobs:
  greeting-job:
    runs-on: ubuntu-latest
    steps:
      - name: "Say Hello Mona its Monday"
        run: "$Greeting My name is $Name and today is $DAY_OF_THE_WEEK !"